version: '3.7'

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  db: